[package]
name = "reader_for_microxml"
version = "1.0.4"
authors = ["Luciano Bestia <luciano.bestia@gmail.com>"]
edition = "2018"
description = "reader for microXml"
repository = "https://github.com/LucianoBestia/reader_for_microxml"
readme = "README.md"
license = "MIT"
keywords = ["rust", "xml", "microxml"]
categories = ["parsing"]
# publish to crates.io only these files
publish = true
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/lib.rs",
]

[dependencies]

[badges]
maintenance = { status = "passively-maintained" }

